### PR TITLE
Update to Qt 5.15.2

### PR DESCRIPTION
**Pull request by m-bers**

### CODE REVIEW

**Comment by guerinoni** [comment]
@m-bers thanks for your PR
I'm trying locally with Qt 5.15.2 but using ubuntu 18...
With ubuntu 20 there is a package tzdata that requires user input and the build falls in timeout

**Comment by guerinoni** [comment]
@m-bers I opened this #5, it should be enough

**Comment by guerinoni** [comment]
@m-bers In another case I used this, I don't know what way is cleaner... ?

```
RUN which dash &> /dev/null && (\
    echo "dash dash/sh boolean false" | debconf-set-selections && \
    DEBIAN_FRONTEND=noninteractive dpkg-reconfigure dash) || \
    echo "Skipping dash reconfigure (not applicable)"

RUN locale-gen en_US.UTF-8 && update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8
```

**Comment by m-bers** [comment]
@guerinoni using Ben J's method on Server Fault: https://serverfault.com/questions/949991/how-to-install-tzdata-on-a-ubuntu-docker-image
```
RUN apt-get update && DEBIAN_FRONTEND="noninteractive" TZ="America/New_York" apt-get install -y tzdata
```
Will this work? Also since TZ would be set upon container build, might want to add an entrypoint.sh that resets TZ based on an environment variable set when doing `docker run`

From the [Ubuntu docs](https://help.ubuntu.com/community/UbuntuTime), we could do something like this (haven't tested yet): 

```
#!/bin/bash
echo $TZ | sudo tee /etc/timezone
sudo dpkg-reconfigure --frontend noninteractive tzdata
/bin/bash
```

Also thanks for building this--it's already been really useful for me!!

**Comment by guerinoni** [comment]
@m-bers ok with this `apt update && DEBIAN_FRONTEND="noninteractive" TZ="America/Los_Angeles"` seems working... For now I can merge your PR because for this purpose the timezone is not critical... Maybe in future we can pass it as arg...

**Pull request merged**
